from .base import Plugin, Command


class ConfigDebug(Plugin):

    def setup_debug(self):
        self.debug['config_debug'] = Command('config debug', lambda a: a, 'some debug is generated by command')


class HelloDebug(Plugin):

    def setup_debug(self):
        self.debug['hello_debug'] = Command('hello debug', lambda a: a, 'some debug is generated by command')
